SELECT  C.CUR_NOMBRE, B.MATRICULADOS, B.INGRESOS FROM (SELECT CUR_ID, COUNT(ALU_ID) AS MATRICULADOS, SUM(PAGO) AS INGRESOS FROM (
SELECT CUR_ID, ALU_ID, SUM(PAG_IMPORTE) AS PAGO FROM EDUCA..PAGO
GROUP BY CUR_ID, ALU_ID) A
GROUP BY CUR_ID ) B INNER JOIN EDUCA..CURSO C ON B.CUR_ID =C.CUR_ID 
