PRINT '*PREGUNTA 2*'

SELECT A.alu_nombre, SUM(B.pag_importe) AS 'IMPORTE DE PAGO'  FROM EDUCA..ALUMNO A INNER JOIN EDUCA..PAGO B ON A.alu_id =B.alu_id
GROUP BY A.alu_nombre

PRINT '*PREGUNTA 3*'
SELECT A.CUR_NOMBRE AS CURSO, SUM(B.pag_importe) AS 'IMPORTE DE PAGO'  FROM EDUCA..CURSO A INNER JOIN EDUCA..PAGO B ON A.cur_id =B.cur_id
GROUP BY A.CUR_NOMBRE