SELECT C.alu_nombre,B.cur_nombre, 
CASE
   WHEN A.mat_nota BETWEEN 0 AND 9 THEN 'MALO' 
   WHEN A.mat_nota BETWEEN 10 AND 13 THEN 'REGULAR'
   WHEN A.mat_nota  BETWEEN 14 AND 17 THEN 'BUENO'
   WHEN A.mat_nota  BETWEEN 18 AND 20 THEN 'BUENO' END CALIFICACION
  FROM  EDUCA..MATRICULA A
INNER JOIN EDUCA..CURSO B ON A.cur_id = B.CUR_ID 
INNER JOIN EDUCA..ALUMNO C ON A.alu_id = C.alu_id